### PR TITLE
Added new entry content and while hooks

### LINKED ISSUE #40: No entry content "inside" hook or after endwhile hook
After using THA for a while, there are two hooks that I think should really be added. Right now there's no hook for within the actual "content" area of an entry. This makes hooking the the post content along with other post elements a little tricky as it needs to be done with priority juggling and choosing whether or not the content goes on the top or bottom.

The other missing hook is an after endwhile hook. Sometimes you need to hook content after the 
`<?php while ( have_posts() ) : the_post(); ?>` part of a loop but before the `endif` check to see if the loop actually contains post data.

I know there are some old proposals to add more content-specific hooks and things like that, but so far I think these are the only two that can actually cause a problem because they are omitted. Related to #7 and #9

### PR DESCRIPTION
**Pull request by robneu**
This fixes #40

### CODE REVIEW

**Comment by joshuadavidnelson** [comment]
Wouldn't `the_content` [filter](https://codex.wordpress.org/Plugin_API/Filter_Reference/the_content) be a better method in place of the `tha_entry_content` hook? Also, there should be a `tha_content_endwhile_after` hook to be consistent.

**Comment by robneu** [comment]
Filtering the content comes with its own set of issues because it's used by plugins to do all kinds of things. It's also a little weird to isolate `the_content` from `the_excerpt` whereas having this hook means you can just check things like `is_archive` etc depending on how your theme is coded. Having a standard hook location makes life a lot easier.

I'm not opposed to an endwhile before hook, but if we go that route it might make more sense to change it from `endwhile` to `while` and place it after the `if` statement but before the opening of the `while` loop.

**Comment by joshuadavidnelson** [comment]
I think having a `while` hook that's after the if statement, but before the while statement - as well as the endwhile one you have currently - would be great. There are plenty of uses for both of those locations.

Can you not check things like `is_archive` in the filter? You should be able to do just about everything with the content filter. If you added a `tha_content_before` and `tha_content_after` perhaps, that seems more in-line with hooking methods used here and elsewhere.

**Comment by robneu** [comment]
The primary use case for having a content hook would be hooking and unhooking the entire content area conditionally. Basically you'd hook any markup for `the_content` as well as `the_content` itself to this hook and then it can be conditionally removed by plugins and child themes.

I suppose technically can do this by filtering `the_content`, but the wrapping markup in particular would be tricky if not impossible. The other problem with this method is if I filter the content to be empty, I'm probably going to have to do a ton of filter juggling to hook it somewhere other than where it was originally. I'd have to filter it on hook A, then remove the filter on hook B then hook `the_content` to hook C or something along those lines.

I'm kind of thinking out loud here, so if any of this sounds ridiculous or you have an idea of how to do it without filter gymnastics I'd love to hear it.

**Comment by joshuadavidnelson** [comment]
If you wanted to conditionally remove the content or override it with another value based on its location, you could do that with the filter by conditionally returning the content or an empty string. In terms of where you hook in, that would likely just require some testing on what to set the filter priority on the content filter, right? You could hook into the new `tha_while_start` hook or another `tha_` hook prior to the content. But if you're using the hook for markup, you'd want a `_before` _and_ an `_after` hook, so you can close any potential markup meant to wrap the content? That could be done with the filter, too.

I just noticed that if you're hooking `the_content` into `tha_entry_content`, then you'd have a double entry, or you'd have to remove `the_content` from the markup.

Perhaps I'm missing something, which is entirely possible - let me know if I'm just not seeing it.

**Comment by robneu** [comment]
In the example it would cause a double entry if the content were hooked, but I wasn't sure how to handle that. If we did go the before/after route and leave the content unhooked by default then emptying it with a filter on `before` and removing that filter on `after` would probably solve most of the usual weirdness I've run into when dealing with this.

Once that was in place, it should be safe to then hook `the_content` and it's containing markup in any other location which would make me happy. Soooo... with that in mind I'll go ahead and update the PR with these changes and hopefully it'll wind up rolled into THA in the future. :D

**Comment by joshuadavidnelson** [comment]
Awesome! Yea, I think the `before` and `after` route has more universal applications, in addition to being consistent with the hooks used elsewhere in THA. Thanks for hearing me out!

**Comment by robneu** [comment]
One last thing... what do you think we should do about the before/after `while` naming convention? Should we keep after `endwhile` and make before while or make them both `while`?

I think after `while` still makes sense, especially since not all developers will be using a literal `endwhile` and may prefer a closing bracket.

**Comment by joshuadavidnelson** [comment]
Yea, I would just use the `while` with `_before` and `_after` to be consistent. I agree, `endwhile` would be confusing.

**Comment by zamoose** [comment]
I like this approach.

**Comment by robneu** [comment]
:tada:

**Pull request merged**
